version: '3'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    restart: always
    environment:
      NEW_RELIC_APP_NAME: "r-frontend"

  restaurant-service:
    build: ./restaurantService
    ports:
      - '3001:3001'
    restart: always
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_API_KEY}
      NEW_RELIC_APP_NAME: "r-restaurantService"

  checkout-service:
    build: ./checkoutService
    ports:
      - '3002:3002'
    restart: always
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_API_KEY}
      NEW_RELIC_APP_NAME: "r-checkoutService"
    
  menu-service:
    build: ./menuService
    ports:
      - '3003:3003'
    restart: always
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_API_KEY}
      NEW_RELIC_APP_NAME: "r-menuService"






